apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sm-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secret-store 
    kind: SecretStore
  target:
    name: hello
  data:
  - secretKey: value 
    remoteRef:
      key: sm-secret