apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    aws:  
      service: SecretsManager 
      region: us-west-2  
      auth:
        secretRef:
          accessKeyIDSecretRef: 
            name: aws-secret 
            key: access-key  
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret