# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-service-api-ingress
#   annotations:
#     alb.ingress.kubernetes.io/group.name: "sbx"
#     alb.ingress.kubernetes.io/target-type: "ip"
#     external-dns.alpha.kubernetes.io/alias: "true"
#     external-dns.alpha.kubernetes.io/hostname: "cloud-lytx-demo-{{ .Release.Name }}-sbx.aws.drivecaminc.xyz"
#     external-dns.kubernetes.io/managed: "true"
#     kubernetes.io/ingress.class: "alb"
# spec:
#   rules:
#     - host: "cloud-lytx-demo-{{ .Release.Name }}-sbx.aws.drivecaminc.xyz"
#       http:
#         paths:
#           - path: /*
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: {{ .Release.Name }}-service-api
#                 port:
#                   number: {{ .Values.service.targetPort }}
